export const FETCH_TRANSACTIONS_REQUEST = 'FETCH_TRANSACTIONS_REQUEST';
export const FETCH_TRANSACTIONS_SUCESS = 'FETCH_TRANSACTIONS_SUCESS';
export const FETCH_TRANSACTIONS_FAIL = 'FETCH_TRANSACTIONS_FAIL';
export const FETCH_TRANSACTIONS_COMPLETE = 'FETCH_TRANSACTIONS_COMPLETE';
